# Chart Releaser Configuration
owner: rafaribe
git-repo: homelab-assistant
charts-dir: charts
skip-packaging: false
skip-upload: false
skip-existing: true
generate-release-notes: true
release-name-template: "{{ .Name }}-{{ .Version }}"
commit-username: ""
commit-email: ""
index-path: index.yaml
packages-with-index: true
push: true
pr: false
remote: origin
target-branch: gh-pages
package-path: .cr-release-packages
index-dir: .cr-index
# Token will be provided via environment variable CR_TOKEN
