{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "homelab-assistant.namespace" . }}
  labels:
    {{- include "homelab-assistant.labels" . | nindent 4 }}
  {{- with (include "homelab-assistant.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
