{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "volsync-monitor.fullname" . }}
  namespace: {{ include "volsync-monitor.namespace" . }}
  labels:
    {{- include "volsync-monitor.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with (include "volsync-monitor.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
  - interval: {{ .Values.metrics.serviceMonitor.interval }}
    path: /metrics
    port: metrics
    scheme: http
  selector:
    matchLabels:
      {{- include "volsync-monitor.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics
{{- end }}
