version: 2

run:
  timeout: 10m
  go: "1.22"

output:
  format: colored-line-number

# Use default linters (errcheck, govet, ineffassign, staticcheck, unused)
linters:
  enable-all: false
  disable-all: false

issues:
  exclude-rules:
    # Exclude kubebuilder generated files
    - path: zz_generated\.deepcopy\.go
      linters:
        - all
    # Allow unchecked errors in test files for cleanup operations
    - path: _test\.go
      linters:
        - errcheck
  exclude:
    # Ignore defer cleanup errors in tests
    - "Error return value of.*is not checked"
