# golangci-lint configuration compatible with v1.61.0
# This version matches the GitHub Action to ensure consistency

run:
  timeout: 10m
  go: "1.22"

output:
  formats:
    - format: colored-line-number

# Use default linters (errcheck, govet, ineffassign, staticcheck, unused)
linters:
  enable-all: false
  disable-all: false

issues:
  exclude-rules:
    # Exclude kubebuilder generated files from all linters
    - path: zz_generated\.deepcopy\.go
      linters:
        - all
