run:
  timeout: 10m
  go: "1.22"

output:
  formats:
    - format: colored-line-number

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unused
    - errcheck
    - gosimple
    - goconst
    - copyloopvar  # Replaces exportloopref for Go 1.22+
  disable:
    - exportloopref  # Deprecated in favor of copyloopvar

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
  goimports:
    local-prefixes: github.com/rafaribe/homelab-assistant

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    # Exclude kubebuilder generated files
    - path: zz_generated\.deepcopy\.go
      linters:
        - all
    # Exclude main.go from some checks
    - path: cmd/main\.go
      linters:
        - gocyclo
