---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - homelab.rafaribe.com
  resources:
  - volsyncmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - homelab.rafaribe.com
  resources:
  - volsyncmonitors/finalizers
  verbs:
  - update
- apiGroups:
  - homelab.rafaribe.com
  resources:
  - volsyncmonitors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - homelab.rafaribe.com
  resources:
  - volsyncunlocks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - homelab.rafaribe.com
  resources:
  - volsyncunlocks/finalizers
  verbs:
  - update
- apiGroups:
  - homelab.rafaribe.com
  resources:
  - volsyncunlocks/status
  verbs:
  - get
  - patch
  - update
