# permissions for end users to view volsyncunlocks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: volsyncunlock-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: homelab-assistant
    app.kubernetes.io/part-of: homelab-assistant
    app.kubernetes.io/managed-by: kustomize
  name: volsyncunlock-viewer-role
rules:
- apiGroups:
  - homelab.rafaribe.com
  resources:
  - volsyncunlocks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - homelab.rafaribe.com
  resources:
  - volsyncunlocks/status
  verbs:
  - get
