---
name: "Chart Testing"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "charts/**"
      - ".github/workflows/chart-test.yaml"
  push:
    branches:
      - main
    paths:
      - "charts/**"
      - ".github/workflows/chart-test.yaml"

jobs:
  chart-test:
    name: Chart Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Install helm unittest plugin
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Run helm unittest
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          for chart in charts/*/; do
            if [ -d "$chart/tests" ]; then
              echo "Running tests for $chart"
              helm unittest "$chart"
            else
              echo "No tests found for $chart, skipping"
            fi
          done

      # Note: chart-testing install is disabled to prevent accidental connection to real clusters
      # - name: Create kind cluster
      #   if: steps.list-changed.outputs.changed == 'true'
      #   uses: helm/kind-action@v1.8.0
      # 
      # - name: Run chart-testing (install)
      #   if: steps.list-changed.outputs.changed == 'true'
      #   run: ct install --target-branch ${{ github.event.repository.default_branch }}

  chart-docs:
    name: Chart Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install helm-docs
        run: |
          cd /tmp
          wget https://github.com/norwoodj/helm-docs/releases/download/v1.14.2/helm-docs_1.14.2_Linux_x86_64.tar.gz
          tar -xzf helm-docs_1.14.2_Linux_x86_64.tar.gz
          sudo mv helm-docs /usr/local/bin/helm-docs
          chmod +x /usr/local/bin/helm-docs

      - name: Run helm-docs
        run: |
          cd charts
          helm-docs --chart-search-root=.
          
      - name: Check for documentation changes
        run: |
          if ! git diff --exit-code; then
            echo "Documentation is out of date. Please run 'make chart-docs' and commit the changes."
            exit 1
          fi
